### ISSUE TITLE
I can't knap my flint!

### ISSUE THREAD

**Issue by SpiderC06** [An-Sar/PrimalCore#19]
The console tab shows an error (I'm using 1.3.0 version (MultiMC) of the Banished! Modpack, http://www.technicpack.net/modpack/banished-harsh-survival.887943, and the config file is: http://pastebin.com/5xL7zjYb)
There is the error:
[12:14:52] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_111]
	at nmd.primal.core.common.CommonUtils.randomCheck(CommonUtils.java:40) ~[CommonUtils.class:?]
	at nmd.primal.core.common.crafting.CraftingEvents.onPlayerInteract(CraftingEvents.java:97) ~[CraftingEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_154_CraftingEvents_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:994) ~[ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:145) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[12:14:52] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@44e9e8aa:
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_111]
	at nmd.primal.core.common.CommonUtils.randomCheck(CommonUtils.java:40) ~[CommonUtils.class:?]
	at nmd.primal.core.common.crafting.CraftingEvents.onPlayerInteract(CraftingEvents.java:97) ~[CraftingEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_154_CraftingEvents_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:994) [ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:145) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) [me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[12:14:52] [Server thread/ERROR]: Index: 9 Listeners:
[12:14:52] [Server thread/ERROR]: 0: NORMAL
[12:14:52] [Server thread/ERROR]: 1: ASM: vazkii.quark.tweaks.feature.KnockOnDoors@6cadc0bf leftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[12:14:52] [Server thread/ERROR]: 2: ASM: imc.common.PlayerEventHandler@57e33b77 onPlayerLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[12:14:52] [Server thread/ERROR]: 3: ASM: biomesoplenty.common.handler.AchievementEventHandler@5e68efbb onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:14:52] [Server thread/ERROR]: 4: ASM: minetweaker.mc1102.ForgeEventHandler@3cf6f2a6 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:14:52] [Server thread/ERROR]: 5: ASM: feyberryjam.minecraft.druidry.init.ModEvents@40f173a6 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:14:52] [Server thread/ERROR]: 6: ASM: toughasnails.handler.AchievementEventHandler@220f4b93 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:14:52] [Server thread/ERROR]: 7: ASM: com.workshopcraft.simplebarrels.handlers.BarrelHandler@19c82208 LeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[12:14:52] [Server thread/ERROR]: 8: LOWEST
[12:14:52] [Server thread/ERROR]: 9: ASM: nmd.primal.core.common.crafting.CraftingEvents@fcad0bd onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
[12:14:52] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_111]
	at nmd.primal.core.common.CommonUtils.randomCheck(CommonUtils.java:40) ~[CommonUtils.class:?]
	at nmd.primal.core.common.crafting.CraftingEvents.onPlayerInteract(CraftingEvents.java:97) ~[CraftingEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_154_CraftingEvents_onPlayerInteract_LeftClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:994) ~[ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:145) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by SpiderC06** [comment]
Fixes, i were using a older version of the mod.

**Comment by An-Sar** [comment]
cool, glad it's working for you now.
