### ISSUE TITLE
(Birch)Barrels leading to Java/Gamecrash

### ISSUE THREAD

**Issue by courseofra** [An-Sar/PrimalCore#195]
Hi there,

Minecraft 1.12.2
Forge 14.23.3.2675
PrimalCore-1.12.2-0.6.54

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

I'm getting this when placing (Birch)Barrels:

[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class nmd.primal.core.api.interfaces.types.ITypeBarrels$EnumType, values=[oak, spruce, birch, jungle, acacia, dark_oak, ironwood, yew, lacquer, corypha]} as it does not exist in BlockStateContainer{block=null, properties=[]}
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at nmd.primal.core.api.interfaces.types.ITypeBarrels.getTypeHardness(ITypeBarrels.java:34)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at nmd.primal.core.common.blocks.storage.Barrel.func_176195_g(Barrel.java:736)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:407)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at com.TominoCZ.FBP.block.FBPAnimationDummyBlock.func_176195_g(FBPAnimationDummyBlock.java:154)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.darkhax.wawla.plugins.generic.PluginHarvestability.getEffectiveTool(PluginHarvestability.java:120)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.darkhax.wawla.plugins.generic.PluginHarvestability.addTileInfo(PluginHarvestability.java:45)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.darkhax.wawla.engine.waila.TileProvider.getWailaBody(TileProvider.java:50)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at mcp.mobius.waila.api.impl.MetaDataProvider.handleBlockTextData(MetaDataProvider.java:120)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:81)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_177_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class nmd.primal.core.api.interfaces.types.ITypeBarrels$EnumType, values=[oak, spruce, birch, jungle, acacia, dark_oak, ironwood, yew, lacquer, corypha]} as it does not exist in BlockStateContainer{block=null, properties=[]}
[18:04:38] [main/INFO] [STDERR]: [com.TominoCZ.FBP.block.FBPAnimationDummyBlock:func_176195_g:157]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)

**Comment by An-Sar** [comment]
i can't reproduce this crash, but based on the log have added so safety checks that should prevent the crash, are you willing to test a dev build?

**Comment by courseofra** [comment]
Hi,

thanks for your investigation.
Of course i can test a dev build. I think tomorrow in the evening (UTC +2).

**Comment by An-Sar** [comment]
https://www.dropbox.com/s/748t85rwrbt5uay/PrimalCore-1.12.2-0.6.54.6.jar?dl=0

**Comment by An-Sar** [comment]
Here is a dev build, if you get the chance, let me know if the crash still occurs 
https://www.dropbox.com/s/748t85rwrbt5uay/PrimalCore-1.12.2-0.6.54.6.jar?dl=0
