### ISSUE TITLE
Jump in barrel with millk [crash]

### ISSUE THREAD

**Issue by Komplein** [An-Sar/PrimalCore#287]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at nmd.primal.core.common.blocks.machines.Barrel.func_180634_a(Barrel.java:530)

-- Block being collided with --
Details:
	Block: primal:barrel[covered=true,type=oak]
	Block location: World: (973,73,367), Chunk: (at 13,4,15 in 60,22; contains blocks 960,0,352 to 975,255,367), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1044)

-- Entity being checked for collision --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 254
	Entity Name: Komplein
	Entity's Exact location: 973.51, 73.30, 367.45
	Entity's Block location: World: (973,73,367), Chunk: (at 13,4,15 in 60,22; contains blocks 960,0,352 to 975,255,367), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.00, -0.16, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:964)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70091_d(GCEntityPlayerMP.java:50)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1951)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2386)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 254
	Entity Name: Komplein
	Entity's Exact location: 973.51, 73.30, 367.45
	Entity's Block location: World: (973,73,367), Chunk: (at 13,4,15 in 60,22; contains blocks 960,0,352 to 975,255,367), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.00, -0.16, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@2e5e9310
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by An-Sar** [comment]
i have a [dev build](https://www.dropbox.com/s/ariqz04h6p938mt/PrimalCore-1.12.2-0.6.103.1.jar?dl=0) with a possible fix, but since i can't immediately reproduce the problem this is kind of shot in the dark. if you can test let me know how it goes. thanks

**Comment by Komplein** [comment]
Okey, i'll try )

**Comment by Komplein** [comment]
Nope. Doesn't work
[crash-2018-11-13_14.51.57-server.txt](https://github.com/An-Sar/PrimalCore/files/2576122/crash-2018-11-13_14.51.57-server.txt)
If i try load old world
[crash-2018-11-13_14.57.57-server.txt](https://github.com/An-Sar/PrimalCore/files/2576135/crash-2018-11-13_14.57.57-server.txt)
If i try jump in barrel in new superflat world
It's pretty unique situation. Maybe simply don't allow to fill barell with milk in next hotfix? World save i didn't need, but save backup of modpack, and if you need will send you (multimc core)

**Comment by An-Sar** [comment]
what kind of milk is it?

**Comment by An-Sar** [comment]
vanilla milk isn't really a fluid so another mod must be registering it as one.

**Comment by Komplein** [comment]
On vanilla with primal i can't storage vanilla milk  at all. Tested. It works. Old world sucsessfull loaded. Thank you for work. Great mod, great developer. =)

**Comment by An-Sar** [comment]
nice, glad it worked. i appreciate the issue reporting and testing.
