### ISSUE TITLE
FluidBlock issue with Primal... Or?

### ISSUE THREAD

**Issue by liquidblur** [An-Sar/PrimalCore#301]
https://paste.dimdev.org/xidusirike.mccrash

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2019-01-06 14:53:47 PST
Description: Initializing game

java.lang.NullPointerException
    at nmd.primal.core.common.helper.RegistryHelper.registerFluidBlock(RegistryHelper.java:120)
    at nmd.primal.core.common.init.ModFluids$RegistrationHandler.registryFluidBlocks(ModFluids.java:94)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_826_RegistrationHandler_registryFluidBlocks_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:775)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3930)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by liquidblur** [comment]
this error is brought on when both primal core and TechStack-s-HeavyMachineryMod mod are installed. have posted it on their github aswell

**Comment by RenanVieira88** [comment]
I can confirm, the same here

**Comment by An-Sar** [comment]
i've added a check against the fluid registry that avoids the crash. the conflicting fluid was bitumen.

**Comment by An-Sar** [comment]
0.6.105 has been released this should be fully resolved
