### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Water-Moon** [An-Sar/PrimalCore#396]
I did nothing and my game crashed. It appeared from the error stack trace that it is caused by Primal Core.

```
java.lang.StackOverflowError
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
    at nmd.primal.core.common.helper.CommonUtils.hasNearByMaterial(CommonUtils.java:261)
    at nmd.primal.core.common.blocks.saxum.MudDrying.updateTick(MudDrying.java:99)

---The code below repeated about 200 times---
    at net.minecraft.world.WorldServer.updateBlockTick(WorldServer.java:551)
    at net.minecraft.world.WorldServer.scheduleUpdate(WorldServer.java:531)
    at nmd.primal.core.api.PrimalAPI.scheduleBlock(PrimalAPI.java:1578)
    at nmd.primal.core.api.PrimalAPI.scheduleBlock(PrimalAPI.java:1599)
    at nmd.primal.core.common.blocks.saxum.MudDrying.updateTick(MudDrying.java:130)
---------------------------------------------
```

[crash-2021-03-06_17.12.58-server.txt](https://github.com/An-Sar/PrimalCore/files/6096270/crash-2021-03-06_17.12.58-server.txt)

**Comment by gatoborrachon** [comment]
Sorry for late reply, you know, the authors doesn't care anymore about the 1.12 version of their mod even if it's the only "complete" version they have.

Can you access to the world and see what is happening with this mud block?

```
-- Block being updated --
  Source block type: ID #0 (tile.air // net.minecraft.block.BlockAir // minecraft:air)
  Block: primal:mud_wet[moisture=wet]
  Block location: World: (-89,64,301), Chunk: (at 7,4,13 in -6,18; contains blocks -96,0,288 to -81,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
```

maybe something strange happened with its surroundings, i have a big personal modpack and i dried a lot of mud blocks without issues

**Comment by Water-Moon** [comment]
Well, it's pretty awkward that nothing happens when the world reloads. 
In other words, only when a world is generated for the first time this occurs, which looks like some strange glitch with Minecraft itself...

It's such a sad story that the author never made this mod open source so that no fix or pull requests could be submitted, and we couldn't even do a code analytics to find what went wrong.

**Comment by gatoborrachon** [comment]
yeah, they simply don't want to open their code, not even the addons have their SourceCode open, but if that issue only happens 1 time at the start of a new world, maybe its acceptable, just use VanillaFix to avoid start minecraft from zero

also, if you really like Kitsu's Forgecraft, send me a message via discord: cato#6876
