### ISSUE TITLE
Dedicated server crash with Alligator

### ISSUE THREAD

**Issue by cosmicdan** [An-Sar/PrimalCore#76]
On latest 1.12.1 release.

````

[16:59:56] [Server thread/ERROR]: Encountered an unexpected exception
--
net.minecraft.util.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19) ~[wp.class:?]
at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:123) ~[xo.class:?]
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346) ~[vp.class:?]
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]
at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?]
at nmd.primal.core.common.entities.living.EntityGator.func_70636_d(EntityGator.java:231) ~[EntityGator.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166) ~[vp.class:?]
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
at net.minecraft.world.World.func_72866_a(World.java:1983) ~[amu.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833) ~[oo.class:?]
at net.minecraft.world.World.func_72870_g(World.java:1945) ~[amu.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1755) ~[amu.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
````

Cheers.

**Comment by cosmicdan** [comment]
Similar crash in SSP:

````
java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:123)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:894)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:689)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at nmd.primal.core.common.entities.living.EntityCanisCampestris.func_70636_d(EntityCanisCampestris.java:414)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at nmd.primal.core.common.entities.living.EntityCanisCampestris.func_70071_h_(EntityCanisCampestris.java:435)
	at net.minecraft.world.World.func_72866_a(World.java:1983)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1945)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by An-Sar** [comment]
Which version are using?

**Comment by cosmicdan** [comment]
1.12.1-0.5.8.

May be triggered by a mod conflict, probably should of tried that first.

**Comment by Dulciphi** [comment]
I've just replicated this now for the first time in SSP. I was using a BOP world type (Every other time I was using a default world type). I don't know why I'm only crashing now that I'm trying to load a BOP world type because the error mentions .EntityAgeable.func. That's from Harder Farming (I think) which is part of [Reasonable Realism](https://github.com/Draco18s/ReasonableRealism). 

The entity aging function causes animals to age, breed and die off 'in the wild'. I can see if I'm able to turn the function off for your mobs and see if that stops the issue from occurring. 


// Uh... Did I do that?

Time: 9/13/17 12:58 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:123)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:894)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:689)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at nmd.primal.core.common.entities.living.EntityBlackBear.func_70071_h_(EntityBlackBear.java:156)
	at net.minecraft.world.World.func_72866_a(World.java:1983)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1945)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:123)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:894)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:689)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at nmd.primal.core.common.entities.living.EntityBlackBear.func_70071_h_(EntityBlackBear.java:156)
	at net.minecraft.world.World.func_72866_a(World.java:1983)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1945)

-- Entity being ticked --
Details:
	Entity Type: primal:bear_black (nmd.primal.core.common.entities.living.EntityBlackBear)
	Entity ID: 107
	Entity Name: Black Bear
	Entity's Exact location: -208.71, 79.00, 3.41
	Entity's Block location: World: (-209,79,3), Chunk: (at 15,4,3 in -14,0; contains blocks -224,0,0 to -209,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: Reign2 CoG1
	All players: 1 total; [EntityPlayerMP['Dulciphi'/2633, l='Reign2 CoG1', x=-97.50, y=67.00, z=103.50]]
	Chunk stats: ServerChunkCache: 769 Drop: 0
	Level seed: 1024124418744405532
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-95,64,101), Chunk: (at 1,4,5 in -6,6; contains blocks -96,0,96 to -81,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 61 game time, 61 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 88470 (now: false), thunder time: 118818 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by cosmicdan** [comment]
EntityAgeable is a vanilla thing. Unrelated.

Could be BoP related. We were using it on the server. I can't remember if my second stacktrace (first reply) from single-player was with Default worldtype or BoP though.

**Comment by srwadleigh** [comment]
Are you able to reliably reproduce the crash or is it more random?

**Comment by An-Sar** [comment]
Let me know if you are able to reproduce the crash, I am doing some testing on my end but so far haven't experienced it.

**Comment by Dulciphi** [comment]
I got it again the very next time I started up my instance after reporting it here, and I've had it every time I've loaded a new BOP world since. Sometimes it crashes as soon as I spawn. Other times it takes a couple of minutes of moving around. I expect this delay is due to the relevant entities spawning in specific biomes. I spawned in a Tundra and moved toward the forest when this latest crash happened.

Now that I can reproduce it consistently within 5 mins of starting a new world, I'll start removing/changing mods to narrow it down. This could be a Foamfix issue for all I know right now.

[Full log](https://paste.ee/p/81VnZ)

**Comment by An-Sar** [comment]
This has been narrowed down to a conflict with Harder Farming. 
And it appears to conflict with other mods as well:

https://github.com/Draco18s/ReasonableRealism/issues/11

**Comment by cosmicdan** [comment]
No problem, thanks for the info.

We’ve actually moved on from both Reasonable Realism mods (performance and compatibility issues still) and Primal Core (does a bit too much, closed source) – so you’re more than welcome to close this issue.

Regards,
Daniel Connolly

**Comment by An-Sar** [comment]
No worries, this has been reported by other people so I'm going to follow through on making sure it's not anything on my end. Testing an updated build of Harder Farming now.

**Comment by An-Sar** [comment]
I believe this has been resolved on the Reasonable Realism side
